version: '3'

networks:
  blinko-network:
    driver: bridge

services:
  blinko-website:
    container_name: blinko-website
    build:
      context: .
      args:
        USE_MIRROR: "true"  
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
      NEXTAUTH_URL: http://localhost:1111
      NEXT_PUBLIC_BASE_URL: http://localhost:1111
      NEXTAUTH_SECRET: y0BOV3GgcLEEpEIq5y2RuGi9h6ck8cVQYBAnLQvZjqo=
      DATABASE_URL: postgresql://postgres:postgres@localhost:5435/postgres
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    ports:
      - 1111:1111
    healthcheck:
      test: ["CMD", "curl", "-f", "http://blinko-website:1111/"]
      interval: 30s 
      timeout: 10s  
      retries: 5
      start_period: 30s
    networks:
      - blinko-network

  postgres:
    image: postgres:14
    container_name: blinko-postgres
    restart: always
    ports:
      - 5435:5432  # Changed the external port to 5435
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - blinko-network
